version: '3.5'

services:
  database:
    image: postgres:11
    restart: on-failure
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
  server:
    image: node:11
    restart: on-failure
    working_dir: /app
    command: >
      bash -c "
        ./node_modules/.bin/ts-node -r tsconfig-paths/register ./src/Server/migrate.ts &
        ./node_modules/.bin/nodemon -e ts -w ./src --ignore ./src/Client -x ./node_modules/.bin/ts-node -r tsconfig-paths/register src/Server/server.ts
      "
    ports:
      - "3000:3000"
    volumes:
      - $PWD:/app
  watch_extension_content:
    image: node:11
    restart: on-failure
    working_dir: /app
    command: >
      bash -c "
        ./node_modules/.bin/webpack --color --config=webpack.extensionContent.config.js --build;
        ./node_modules/.bin/webpack --color --config=webpack.extensionContent.config.js --watch
      "
    volumes:
      - $PWD:/app
  watch_web_app:
    image: node:11
    restart: on-failure
    working_dir: /app
    command: >
      bash -c "
        ./node_modules/.bin/webpack --color --config=webpack.webApp.config.js --build;
        ./node_modules/.bin/webpack --color --config=webpack.webApp.config.js --watch
      "
    volumes:
      - $PWD:/app
volumes:
  database:
