version: '3.5'

services:
  database:
    image: postgres:11
    restart: on-failure
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
  server:
    image: node:11
    restart: on-failure
    working_dir: /app
    command: ./node_modules/.bin/nodemon -e ts -w ./src -x ./node_modules/.bin/ts-node -r tsconfig-paths/register src/Server/server.ts
    ports:
      - "3000:80"
    volumes:
      - $PWD:/app
  extension_watch:
    image: node:11
    restart: on-failure
    working_dir: /app
    command: |
      ./node_modules/.bin/webpack --build
      ./node_modules/.bin/webpack --watch
    volumes:
      - $PWD:/app
volumes:
  database:
