version: '3.8'

services:
  database:
    image: postgres:11
    restart: on-failure
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
    # logging:
    #   driver: local
    #   options:
    #     max-size: "20m"
    #     max-file: "10"
    #     compress: "false"
  server_watch:
    image: node:14
    restart: on-failure
    working_dir: /app
    environment:
      - KANJIMI_DATABASE_HOST=database
      - KANJIMI_DATABASE_PORT=5432
      - KANJIMI_DATABASE_DATABASE=test
      - KANJIMI_DATABASE_USER=test
      - KANJIMI_DATABASE_PASSWORD=test
      - KANJIMI_ALLOW_TEST_PAGES=true
      - KANJIMI_SMTP_HOST=smtp
      - KANJIMI_SMTP_PORT=25
      - KANJIMI_SMTP_SECURE=false
      #- KANJIMI_SMTP_USER=
      #- KANJIMI_SMTP_PASS=
      - KANJIMI_API_URL=http://localhost:3000/api
      - KANJIMI_WWW_URL=http://localhost:3000/www
    command: >
      bash -c "
        ./node_modules/.bin/nodemon \
          -e ts \
          -w ./src \
          --ignore ./src/Extension \
          --ignore ./src/WebApp \
          --ignore './src/**/*.test.*' \
          --ignore './src/**/*.e2e.*' \
          -x ./node_modules/.bin/tsc \
          -p ./src/Server/tsconfig.json
      "
    volumes:
      - $PWD:/app
  server:
    image: node:14
    restart: on-failure
    working_dir: /app
    depends_on:
      - database
    environment:
      - NODE_PATH=server/
      - KANJIMI_DATABASE_HOST=database
      - KANJIMI_DATABASE_PORT=5432
      - KANJIMI_DATABASE_DATABASE=test
      - KANJIMI_DATABASE_USER=test
      - KANJIMI_DATABASE_PASSWORD=test
      - KANJIMI_ALLOW_TEST_PAGES=true
      - KANJIMI_SMTP_HOST=smtp
      - KANJIMI_SMTP_PORT=25
      - KANJIMI_SMTP_SECURE=false
      #- KANJIMI_SMTP_USER=
      #- KANJIMI_SMTP_PASS=
      - KANJIMI_API_URL=http://localhost:3000/api
      - KANJIMI_WWW_URL=http://localhost:3000/www
    #resources:
    #  limits:
    #    cpus: "1.0"
    #    memory: 512M
    command: >
      bash -c "
        node -r tsconfig-paths/register ./server/Server/migrate.js &
        ./node_modules/.bin/nodemon -w ./server -x node --expose-gc server/Server/server.js
      "
    healthcheck:
      test: curl http://localhost:3000/www/
      interval: 15s
      timeout: 3s
      retries: 3
      start_period: 45s
    ports:
      - "3000:3000"
    volumes:
      - $PWD:/app
      - mails:/tmp/mails
    #logging:
    #  driver: local
    #  options:
    #    max-size: "20m"
    #    max-file: "10"
    #    compress: "false"
  extension:
    image: node:14
    restart: on-failure
    working_dir: /app
    environment:
      - KANJIMI_API_URL=http://localhost:3000/api
      - KANJIMI_WWW_URL=http://localhost:3000/www
    command: >
      bash -c "
        ./node_modules/.bin/webpack --color --config=src/Extension/webpack.config.js --build;
        ./node_modules/.bin/webpack --color --config=src/Extension/webpack.config.js --watch
      "
    healthcheck:
      test: cat ./extension/content.build.js
      interval: 3s
      timeout: 1s
      retries: 3
      start_period: 30s
    volumes:
      - $PWD:/app
  webapp:
    image: node:14
    restart: on-failure
    working_dir: /app
    environment:
      - KANJIMI_API_URL=http://localhost:3000/api
      - KANJIMI_WWW_URL=http://localhost:3000/www
    command: >
      bash -c "
        ./node_modules/.bin/webpack --color --config=src/WebApp/webpack.config.js --build;
        ./node_modules/.bin/webpack --color --config=src/WebApp/webpack.config.js --watch
      "
    healthcheck:
      test: cat ./www/js/app.build.js
      interval: 3s
      timeout: 1s
      retries: 3
      start_period: 30s
    volumes:
      - $PWD:/app
  smtp:
    image: hmlio/spamsink
    restart: on-failure
    environment:
      - SINK_PORT=25
      - SINK_HOSTNAME=smtp
    volumes:
      - mails:/opt/spamsink/mails
volumes:
  database:
  mails:
