version: '3.5'

services:
  database:
    image: postgres:11
    restart: on-failure
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
  server:
    image: node:11
    restart: on-failure
    working_dir: /app
    command: npm run server:watch
    ports:
      - "3000:80"
    volumes:
      - $PWD:/app
  extension:
    image: joenyland/nodejs-firefox-chrome
    restart: always
    working_dir: /app
    command: npm run extension:watch
    environment:
      - DISPLAY=${DISPLAY_MAC}
    volumes:
      - $PWD:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority
volumes:
  database:
