version: '3.5'

services:
  database:
    image: postgres:11
    restart: on-failure
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - "5432:5432"
