version: '3.8'

services:
  database:
    image: postgres:11
    restart: on-failure
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
  watch:
    image: node:14-alpine
    restart: on-failure
    working_dir: /app
    command: ./node_modules/.bin/tsc --watch -p ./src/Server/tsconfig.json
    volumes:
      - $PWD:/app
  server:
    image: node:14-alpine
    restart: on-failure
    working_dir: /app
    depends_on:
      - database
      - watch
    env_file:
      - docker-compose.env
    #resources:
    #  limits:
    #    cpus: "1.0"
    #    memory: 512M
    command: >
      sh -c "
        while [ ! -f ./server/Server/server.js ]; do
          echo 'Waiting for the server source files...'
          sleep 1
        done;
        ./node_modules/.bin/nodemon -w ./server --expose-gc server/Server/server.js
      "
    #command: ./node_modules/.bin/nodemon -w ./server --inspect=0.0.0.0:9229 --expose-gc server/Server/server.js
    healthcheck:
      test: wget -q https://localhost:3000/api/health-check/ -O /dev/null --no-check-certificate
      interval: 15s
      timeout: 3s
      retries: 3
      start_period: 2m
    ports:
      - "3000:3000"
      #- "9229:9229"
    volumes:
      - $PWD:/app
      - mails:/tmp/mails
    #logging:
    #  driver: local
    #  options:
    #    max-size: "20m"
    #    max-file: "10"
    #    compress: "false"
  migrate:
    image: node:14-alpine
    restart: on-failure
    working_dir: /app
    depends_on:
      - database
      - watch
    env_file:
      - docker-compose.env
    command: >
      sh -c "
        while [ ! -f ./server/Server/migrate.js ]; do
          echo 'Waiting for the migrate source files...'
          sleep 1
        done;
        node server/Server/migrate.js
      "
    volumes:
      - $PWD:/app
  extension:
    image: node:14-alpine
    restart: on-failure
    working_dir: /app
    env_file:
      - docker-compose.env
    command: >
      sh -c "
        ./node_modules/.bin/webpack --color --config=src/Extension/webpack.config.js --build;
        ./node_modules/.bin/webpack --color --config=src/Extension/webpack.config.js --watch
      "
    healthcheck:
      test: cat ./extension/content.build.js
      interval: 3s
      timeout: 1s
      retries: 3
      start_period: 30s
    volumes:
      - $PWD:/app
  webapp:
    image: node:14-alpine
    restart: on-failure
    working_dir: /app
    env_file:
      - docker-compose.env
    command: >
      sh -c "
        ./node_modules/.bin/webpack --color --config=src/WebApp/webpack.config.js --build;
        ./node_modules/.bin/webpack --color --config=src/WebApp/webpack.config.js --watch
      "
    healthcheck:
      test: cat ./www/js/app.build.js
      interval: 3s
      timeout: 1s
      retries: 3
      start_period: 30s
    volumes:
      - $PWD:/app
  smtp:
    image: hmlio/spamsink
    restart: on-failure
    environment:
      - SINK_PORT=25
      - SINK_HOSTNAME=smtp
    volumes:
      - mails:/opt/spamsink/mails
volumes:
  database:
  mails:
