enum VerbFormType {
	CAUSATIVE,
	CONDITIONAL,
	IMPERATIVE,
	NEGATIVE,
	PASSIVE,
	PAST,
	PLAIN,
	POLITE,
	POTENTIAL,
	PROHIBITIVE,
	STEM,
	TE,
	VOLITIONAL,
	POLITE_NEGATIVE,

	// TODO + past
		// past for polite, passive, causative, potential, polite_negative

	PASSIVE_NEGATIVE,
	CAUSATIVE_NEGATIVE,
	POTENTIAL_NEGATIVE,

	PASSIVE_POLITE,
	CAUSATIVE_POLITE,
	POTENTIAL_POLITE,

	PASSIVE_POLITE_NEGATIVE,
	CAUSATIVE_POLITE_NEGATIVE,
	POTENTIAL_POLITE_NEGATIVE,

	POLITE_VOLITIONAL,
	POLITE_PAST,
}

export default VerbFormType;
