name: tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt-get install firefox
    - run: npm install
    - run: docker-compose up -d --build
    - run: make test
    - run: while [ ! -f ./extension/content.build.js ]; do sleep 1; done; ls -R ./extension
    - run: while [ ! -f ./www/js/app.build.js ]; do sleep 1; done; ls -R ./www
    - run: make e2e
    - run: docker-compose logs
      if: failure()
    - name: Uploads the cypress videos
      if: failure()
      uses: actions/upload-artifact@v1
      with:
        name: cypress-videos
        path: cypress/videos
